[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
hex = "0.4.3"
risc0-build = { version = "0.21.0" }
risc0-zkp = "0.21.0"

[package.metadata.risc0]
methods = ["guest"]
