gen: generate-abi

generate-abi:
	solc --abi \
	contracts/dataverse/contracts/extension/relayer/IDataverseRelayer.sol \
	contracts/dataverse/contracts/extension/verifier/IDataverseVerifier.sol \
	-o contracts/abi --overwrite