name: build-devcontainers-image

on:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/*"
  pull_request:
    paths:
      - ".devcontainer/*"

env:
  CONTAINER: dataverse-node

jobs:
  build:
    name: Build
    if: github.repository_owner == 'dataverse-os'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: setup devpod
        run: curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod

      - name: build prebuild
        run: |
          devpod provider add docker
          devpod build .
